# Generated by Django 6.0 on 2026-01-02 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='sku',
            new_name='stock_unit',
        ),
    ]
